#!/usr/bin/env python3
"""Derive a deterministic Surface Manifest and Rust descriptor table from Chrome evidence."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any


MANIFEST_VERSION = 1


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def callable_spec(value: dict[str, Any] | None) -> dict[str, Any] | None:
    if value is None:
        return None
    return {
        "name": value["name"],
        "length": value["length"],
        "native_like": value["native_like"],
    }


def member_owner(path: str, value_type: str) -> str:
    if path == "globalThis":
        return "global"
    if path.endswith(".prototype"):
        return "prototype"
    if value_type == "function":
        return "constructor"
    return "instance"


def slug(value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").lower()
    return normalized or "anonymous"


def handler_id(path: str, key: str, descriptor: dict[str, Any]) -> str:
    known = {
        ("globalThis", "atob"): "encoding.atob",
        ("globalThis", "btoa"): "encoding.btoa",
        ("globalThis", "performance"): "profile.performance",
        ("globalThis", "navigator"): "profile.navigator",
        ("globalThis", "screen"): "profile.screen",
        ("globalThis", "window"): "global.window",
        ("globalThis", "self"): "global.self",
        ("globalThis", "document"): "dom.document",
        ("Performance.prototype", "now"): "clock.performance_now",
        ("EventTarget.prototype", "addEventListener"): "events.add_listener",
        ("EventTarget.prototype", "removeEventListener"): "events.remove_listener",
        ("EventTarget.prototype", "dispatchEvent"): "events.dispatch",
    }
    if (path, key) in known:
        return known[(path, key)]
    operation = "get" if descriptor["kind"] == "accessor" else "value"
    if descriptor.get("callable") is not None:
        operation = "call"
    return f"generated.{slug(path)}.{slug(key)}.{operation}"


def derive_manifest(snapshot_path: Path) -> dict[str, Any]:
    snapshot_bytes = snapshot_path.read_bytes()
    snapshot = json.loads(snapshot_bytes)
    evidence = {
        "sha256": sha256_bytes(snapshot_bytes),
        "media_type": "application/vnd.yatouv8.chrome-snapshot+json",
    }
    interfaces: list[dict[str, Any]] = []
    for surface in snapshot["surfaces"]:
        if not surface["available"]:
            continue
        own_keys = surface["own_keys"]
        descriptors = surface["descriptors"]
        if len(own_keys) != len(descriptors):
            raise ValueError(f"descriptor/key mismatch: {surface['path']}")
        owner = member_owner(surface["path"], surface["value_type"])
        members = []
        for key, descriptor in zip(own_keys, descriptors, strict=True):
            if key != descriptor["key"]:
                raise ValueError(
                    f"descriptor order mismatch: {surface['path']}.{key['display']}"
                )
            members.append(
                {
                    "key": key,
                    "owner": owner,
                    "descriptor_kind": descriptor["kind"],
                    "configurable": descriptor["configurable"],
                    "enumerable": descriptor["enumerable"],
                    "writable": descriptor.get("writable"),
                    "value_type": descriptor.get("value_type"),
                    "callable": callable_spec(descriptor.get("callable")),
                    "getter": callable_spec(descriptor.get("getter")),
                    "setter": callable_spec(descriptor.get("setter")),
                    "handler_id": handler_id(
                        surface["path"], key["display"], descriptor
                    ),
                    "evidence_refs": [evidence],
                }
            )
        interfaces.append(
            {
                "path": surface["path"],
                "prototype_path": surface["prototype_path"],
                "value_type": surface["value_type"],
                "own_key_order": own_keys,
                "members": members,
            }
        )
    return {
        "schema_version": MANIFEST_VERSION,
        "baseline_id": snapshot["baseline_id"],
        "source_snapshot": evidence,
        "interfaces": interfaces,
    }


def rust_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_rust(manifest: dict[str, Any]) -> str:
    lines = [
        "// @generated by tools/surface-codegen/generate.py; DO NOT EDIT.",
        "",
        f"/// Baseline that produced the generated descriptor table.\npub const GENERATED_BASELINE_ID: &str = {rust_string(manifest['baseline_id'])};",
        f"/// SHA-256 of the direct parent Chrome snapshot.\npub const GENERATED_SNAPSHOT_SHA256: &str = {rust_string(manifest['source_snapshot']['sha256'])};",
        "",
        "/// Generated interfaces in accepted Chrome capture order.",
        "pub static GENERATED_INTERFACES: &[GeneratedInterfaceSpec] = &[",
    ]
    offset = 0
    for interface in manifest["interfaces"]:
        prototype = (
            "Some(" + rust_string(interface["prototype_path"]) + ")"
            if interface["prototype_path"] is not None
            else "None"
        )
        length = len(interface["members"])
        lines.extend(
            [
                "    GeneratedInterfaceSpec {",
                f"        path: {rust_string(interface['path'])},",
                f"        prototype_path: {prototype},",
                f"        member_start: {offset},",
                f"        member_len: {length},",
                "    },",
            ]
        )
        offset += length
    lines.extend(["] ;".replace(" ", ""), "", "/// Generated members in exact Chrome own-key order.", "pub static GENERATED_MEMBERS: &[GeneratedMemberSpec] = &["])
    for interface in manifest["interfaces"]:
        for member in interface["members"]:
            kind = (
                "ManifestDescriptorKind::Data"
                if member["descriptor_kind"] == "data"
                else "ManifestDescriptorKind::Accessor"
            )
            writable = (
                "None"
                if member["writable"] is None
                else f"Some({str(member['writable']).lower()})"
            )
            lines.extend(
                [
                    "    GeneratedMemberSpec {",
                    f"        interface: {rust_string(interface['path'])},",
                    f"        key: {rust_string(member['key']['display'])},",
                    f"        kind: {kind},",
                    f"        configurable: {str(member['configurable']).lower()},",
                    f"        enumerable: {str(member['enumerable']).lower()},",
                    f"        writable: {writable},",
                    f"        handler_id: {rust_string(member['handler_id'])},",
                    "    },",
                ]
            )
    lines.extend(["];", ""])
    return "\n".join(lines)


def runtime_manifest(manifest: dict[str, Any]) -> dict[str, Any]:
    """Strip evidence payloads while retaining every runtime descriptor field."""

    interfaces = []
    for interface in manifest["interfaces"]:
        members = []
        for member in interface["members"]:
            members.append(
                {
                    "k": member["key"],
                    "d": member["descriptor_kind"],
                    "c": member["configurable"],
                    "e": member["enumerable"],
                    "w": member["writable"],
                    "t": member["value_type"],
                    "f": member["callable"],
                    "g": member["getter"],
                    "s": member["setter"],
                }
            )
        interfaces.append(
            {
                "path": interface["path"],
                "prototype_path": interface["prototype_path"],
                "value_type": interface["value_type"],
                "members": members,
            }
        )
    return {"baseline_id": manifest["baseline_id"], "interfaces": interfaces}


def canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--snapshot", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--rust", type=Path, required=True)
    parser.add_argument("--runtime", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest = derive_manifest(args.snapshot)
    write_if_changed(args.manifest, canonical_json(manifest))
    write_if_changed(args.rust, render_rust(manifest))
    if args.runtime is not None:
        write_if_changed(args.runtime, canonical_json(runtime_manifest(manifest)))
    print(
        json.dumps(
            {
                "baseline_id": manifest["baseline_id"],
                "snapshot_sha256": manifest["source_snapshot"]["sha256"],
                "interface_count": len(manifest["interfaces"]),
                "member_count": sum(
                    len(interface["members"])
                    for interface in manifest["interfaces"]
                ),
                "manifest": str(args.manifest),
                "rust": str(args.rust),
                "runtime": str(args.runtime) if args.runtime is not None else None,
            },
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
